// Procedural Earth — no texture downloads, fully shader-based.
//
// The continents are generated by 3D fbm noise threshold; oceans are shaded
// with a deep-blue gradient + spec rim; clouds are a second translucent
// fbm-noise sphere rotating slightly faster than the surface.
// Vesalius gold-leaf coastlines: a thin gold contour where the noise crosses
// the land/sea threshold.
//
// Atmosphere: a back-side sphere with fresnel that bleeds cyan at the limb.

import { useMemo, useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

const SURFACE_VERTEX = `
  varying vec3 vPos;
  varying vec3 vNormal;
  varying vec3 vViewDir;
  void main() {
    vPos = position;
    vNormal = normalize(normalMatrix * normal);
    vec4 mv = modelViewMatrix * vec4(position, 1.0);
    vViewDir = normalize(-mv.xyz);
    gl_Position = projectionMatrix * mv;
  }
`;

const SURFACE_FRAGMENT = `
  uniform float uTime;
  uniform vec3 uOceanDeep;
  uniform vec3 uOceanShallow;
  uniform vec3 uLand;
  uniform vec3 uLandHigh;
  uniform vec3 uGold;
  varying vec3 vPos;
  varying vec3 vNormal;
  varying vec3 vViewDir;

  float hash(vec3 p) { return fract(sin(dot(p, vec3(127.1, 311.7, 74.7))) * 43758.5453); }
  float noise(vec3 p) {
    vec3 i = floor(p);
    vec3 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    return mix(
      mix(mix(hash(i), hash(i + vec3(1, 0, 0)), f.x), mix(hash(i + vec3(0, 1, 0)), hash(i + vec3(1, 1, 0)), f.x), f.y),
      mix(mix(hash(i + vec3(0, 0, 1)), hash(i + vec3(1, 0, 1)), f.x), mix(hash(i + vec3(0, 1, 1)), hash(i + vec3(1, 1, 1)), f.x), f.y),
      f.z
    );
  }
  float fbm(vec3 p) {
    float v = 0.0;
    float a = 0.55;
    for (int i = 0; i < 6; i++) {
      v += a * noise(p);
      p *= 2.13;
      a *= 0.55;
    }
    return v;
  }

  void main() {
    vec3 p = normalize(vPos);
    float continents = fbm(p * 1.55 + vec3(0.13));
    float landMask = smoothstep(0.50, 0.55, continents);

    // Detail on land
    float detail = fbm(p * 13.0);
    vec3 land = mix(uLand, uLandHigh, smoothstep(0.34, 0.55, continents + detail * 0.21));

    // Oceans
    float oceanDepth = smoothstep(0.21, 0.50, continents);
    vec3 ocean = mix(uOceanDeep, uOceanShallow, oceanDepth);

    vec3 base = mix(ocean, land, landMask);

    // Vesalius gold coastlines — thin band where landMask transitions
    float coast = 1.0 - abs((continents - 0.525) * 21.0);
    coast = clamp(coast, 0.0, 1.0);
    base = mix(base, uGold, coast * 0.55);

    // Day-night terminator: fake light from upper-right
    vec3 lightDir = normalize(vec3(0.55, 0.55, 0.34));
    float lambert = max(dot(vNormal, lightDir), 0.0);
    base *= 0.21 + lambert * 0.89;

    // City lights on the dark side
    float night = 1.0 - lambert;
    float cities = smoothstep(0.55, 0.89, fbm(p * 21.0)) * landMask;
    base += uGold * cities * night * 0.34;

    // Specular highlight on oceans
    vec3 reflectDir = reflect(-lightDir, vNormal);
    float spec = pow(max(dot(reflectDir, vViewDir), 0.0), 21.0) * (1.0 - landMask);
    base += vec3(1.0, 0.95, 0.55) * spec * 0.55;

    gl_FragColor = vec4(base, 1.0);
  }
`;

const ATM_VERTEX = `
  varying vec3 vNormal;
  void main() {
    vNormal = normalize(normalMatrix * normal);
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`;

const ATM_FRAGMENT = `
  varying vec3 vNormal;
  void main() {
    float intensity = pow(0.55 - dot(vNormal, vec3(0.0, 0.0, 1.0)), 2.13);
    gl_FragColor = vec4(0.34, 0.69, 1.0, intensity * 0.55);
  }
`;

const CLOUDS_VERTEX = SURFACE_VERTEX;
const CLOUDS_FRAGMENT = `
  uniform float uTime;
  varying vec3 vPos;
  varying vec3 vNormal;

  float hash(vec3 p) { return fract(sin(dot(p, vec3(127.1, 311.7, 74.7))) * 43758.5453); }
  float noise(vec3 p) {
    vec3 i = floor(p);
    vec3 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    return mix(
      mix(mix(hash(i), hash(i + vec3(1, 0, 0)), f.x), mix(hash(i + vec3(0, 1, 0)), hash(i + vec3(1, 1, 0)), f.x), f.y),
      mix(mix(hash(i + vec3(0, 0, 1)), hash(i + vec3(1, 0, 1)), f.x), mix(hash(i + vec3(0, 1, 1)), hash(i + vec3(1, 1, 1)), f.x), f.y),
      f.z
    );
  }
  float fbm(vec3 p) {
    float v = 0.0;
    float a = 0.55;
    for (int i = 0; i < 5; i++) {
      v += a * noise(p);
      p *= 2.13;
      a *= 0.55;
    }
    return v;
  }

  void main() {
    vec3 p = normalize(vPos);
    float clouds = fbm(p * 5.0 + vec3(uTime * 0.013));
    clouds = smoothstep(0.55, 0.89, clouds);

    vec3 lightDir = normalize(vec3(0.55, 0.55, 0.34));
    float lambert = max(dot(vNormal, lightDir), 0.0);

    gl_FragColor = vec4(vec3(1.0) * (0.34 + lambert * 0.66), clouds * 0.55);
  }
`;

export default function EarthGlobe() {
  const meshRef = useRef<THREE.Mesh>(null);
  const cloudsRef = useRef<THREE.Mesh>(null);
  const atmRef = useRef<THREE.Mesh>(null);

  const surfaceUniforms = useMemo(() => ({
    uTime: { value: 0 },
    uOceanDeep:    { value: new THREE.Color('#021d3a') },
    uOceanShallow: { value: new THREE.Color('#0a4a82') },
    uLand:         { value: new THREE.Color('#1a3d2e') },
    uLandHigh:     { value: new THREE.Color('#5b6e3d') },
    uGold:         { value: new THREE.Color('#D4AF37') },
  }), []);

  const cloudsUniforms = useMemo(() => ({ uTime: { value: 0 } }), []);

  useFrame((state) => {
    surfaceUniforms.uTime.value = state.clock.elapsedTime;
    cloudsUniforms.uTime.value = state.clock.elapsedTime;
    if (meshRef.current) meshRef.current.rotation.y = state.clock.elapsedTime * 0.034;
    if (cloudsRef.current) cloudsRef.current.rotation.y = state.clock.elapsedTime * 0.055;
  });

  return (
    <group>
      <mesh ref={meshRef}>
        <sphereGeometry args={[2.1, 144, 144]} />
        <shaderMaterial uniforms={surfaceUniforms} vertexShader={SURFACE_VERTEX} fragmentShader={SURFACE_FRAGMENT} />
      </mesh>
      <mesh ref={cloudsRef} scale={1.013}>
        <sphereGeometry args={[2.1, 89, 89]} />
        <shaderMaterial
          uniforms={cloudsUniforms}
          vertexShader={CLOUDS_VERTEX}
          fragmentShader={CLOUDS_FRAGMENT}
          transparent
          depthWrite={false}
        />
      </mesh>
      <mesh ref={atmRef} scale={1.13}>
        <sphereGeometry args={[2.1, 55, 55]} />
        <shaderMaterial
          vertexShader={ATM_VERTEX}
          fragmentShader={ATM_FRAGMENT}
          transparent
          side={THREE.BackSide}
          depthWrite={false}
        />
      </mesh>
    </group>
  );
}
